# FastAgent 配置文件

# 默认模型配置
default_model: gpt-4o  # 使用 FastAgent 支持的模型名称

# 日志配置
logger:
  level: "info"
  type: "console"
  progress_display: true
  show_chat: true
  show_tools: true
  truncate_tools: true

# MCP 服务器配置
mcp:
  servers:
    # 我们的组合工具服务器
    combined-tools:
      command: "uv"
      args: ["run", "testsever/main.py"]   
    
    # Fetch服务器
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]

# OpenAI配置
openai:
  default_model: "gpt-4o"
  api_key: "sk-3962e8a22f764dfdb96b2a3e90601cf5"
  api_base: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  max_tokens: 2000
  temperature: 0.7
  
# Anthropic配置 (保留但不使用)
anthropic:
  default_model: "claude-3-haiku-20240307" 